version: "3.8"
services:
  zen:
    image: warriorsfly/zen
    container_name: zen
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    environment:
      - DATABASE_URL=postgres://database/postgres
    depends_on:
      - database

  database:
    image: postgres:alpine
    container_name: database
    environment:
      - POSTGRES_USER=zen
      - POSTGRES_PASSWORD=zen
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgres/data
      - ./migrations/00000000000000_diesel_initial_setup/up.sql:/docker-entrypoint-initdb.d/00000000000000_diesel_initial_setup.sql
      - ./migrations/2019-03-06-144033_create_users/up.sql:/docker-entrypoint-initdb.d/2019-03-06-144033_create_users.sql
      - ./migrations/2019-03-06-144624_create_followers/up.sql:/docker-entrypoint-initdb.d/2019-03-06-144624_create_followers.sql
      - ./migrations/2019-03-06-145146_create_articles/up.sql:/docker-entrypoint-initdb.d/2019-03-06-145146_create_articles.sql
      - ./migrations/2019-03-06-152302_create_comments/up.sql:/docker-entrypoint-initdb.d/2019-03-06-152302_create_comments.sql

    restart: always

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/var/lib/redis/data
  #   restart: always
  # 后面要补上 flutter前端
  # application:
volumes:
  database_data:
    driver: local
  # redis_data:
  #   driver: local
