-- Your SQL goes here
CREATE TABLE product(
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  title VARCHAR(32) NOT NULL DEFAULT '',
  handle VARCHAR(32) NOT NULL DEFAULT '',
  product_type VARCHAR(36) NOT NULL DEFAULT '',
  vendor  VARCHAR(128) NOT NULL DEFAULT '',-- COMMENT '供应商',
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,-- COMMENT '创建时间',
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,-- COMMENT '更新时间',
)